wandb_version: 1

exp_name:
  desc: null
  value: sac
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: crossq
wandb_entity:
  desc: null
  value: noahfarr
capture_video:
  desc: null
  value: false
env_id:
  desc: null
  value: Hopper-v4
total_timesteps:
  desc: null
  value: 1000000
buffer_size:
  desc: null
  value: 1000000
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 256
learning_starts:
  desc: null
  value: 5000.0
policy_lr:
  desc: null
  value: 0.0003
q_lr:
  desc: null
  value: 0.001
policy_frequency:
  desc: null
  value: 2
target_network_frequency:
  desc: null
  value: 1
alpha:
  desc: null
  value: 0.2
autotune:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    code_path: code/sac.py
    python_version: 3.12.3
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718534433
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.12.3
      5: 0.17.1
      8:
      - 4
      - 5
      13: darwin-arm64
